inherit_from: .rubocop_todo.yml


# rspec expect{...} is conventional
Style/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Metrics/LineLength:
  Max: 200
